# Generated by Django 5.1.1 on 2024-09-15 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_delete_moodentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descripton',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='nama',
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
