# Generated by Django 5.1.1 on 2024-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_descripton_products_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='kelas',
            field=models.CharField(default='PBP A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='namaMahasiswa',
            field=models.CharField(default='Crysandya Vic Rajendra', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='npm',
            field=models.IntegerField(default=2306165622),
            preserve_default=False,
        ),
    ]
