# Generated by Django 5.1.1 on 2024-09-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_products_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='products',
            name='namaMahasiswa',
        ),
        migrations.RemoveField(
            model_name='products',
            name='npm',
        ),
    ]
